stages:
  prepare_data:
    cmd: python .\src\data\prepare.py .\data\raw\data.csv
    deps:
    - .\data\raw\data.csv\
    - .\src\data\prepare.py
    outs:
    - .\data\processed\
    params:
    - prepare_data.random_state
    
  train_model:
    cmd: python .\src\models\train.py .\data\processed\
    deps:
    - .\data\processed\
    outs:
    - .\models\
    params:
    - train_model.alpha
    
  evaluate:
    cmd: python .\src\models\evaluate.py .\data\processed\ .\models\
    deps:
    - .\data\processed\
    - .\models\
